djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('pizza/', include('pizza.urls')),
    path('studenci/', include('studenci.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

pizza/urls.py
from django.urls import path

from . import views

app_name = 'pizza'
urlpatterns = [
    path('', views.index, name='index'),
    path('komunikat/', views.komunikat, name='komunikat'),
    path('zamowienie/', views.zamowienie, name='zamowienie'),
]

studenci/urls.py
from django.urls import path

from . import views

app_name = 'studenci'
urlpatterns = [
    path('', views.index, name='index'),
    path('miasta/', views.miasta, name='miasta'),
    path('uczelnie/', views.uczelnie, name='uczelnie'),
    path('login/', views.loguj_studenta, name='login'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('rejestruj/', views.rejestruj, name='rejestruj'),
]

pizza/models.py
from django.db import models

class Pizza(models.Model):
    LARGE = 'L'
    MEDIUM = 'M'
    SMALL = 'S'
    ROZMIARY = (
        (LARGE, 'duża'),
        (MEDIUM, 'średnia'),
        (SMALL, 'mała'),
    )

    nazwa = models.CharField(verbose_name='pizza', max_length=30)
    opis = models.TextField(blank=True, default='', help_text='Opis pizzy')
    rozmiar = models.CharField(max_length=1, choices=ROZMIARY, default=LARGE)
    cena = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    data = models.DateField('dodano', auto_now_add=True)

    def __str__(self):
        return self.nazwa
    class Meta:
        verbose_name_plural = "pizze"

class Składnik(models.Model):
    pizza = models.ManyToManyField(Pizza,
                              related_name='składniki')
    nazwa = models.CharField(verbose_name='składnik', max_length=30)
    jarski = models.BooleanField(verbose_name='jarski?', help_text='Zaznacz Jeżeli składnik jest odpowiedni dla wegetarian', default=False)

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "składniki"

studenci/models.py
from django.db import models


class Miasto(models.Model):
    nazwa = models.CharField(
        verbose_name='miasto',
        max_length=30,
        help_text='Nazwa miasta')
    kod = models.CharField(
        max_length=6,
        help_text='Kod pocztowy')

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "miasta"

class Uczelnia(models.Model):
    nazwa = models.CharField(
        verbose_name='uczelnia',
        max_length=30,
        help_text='Nazwa uczelni')

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "uczelnie"

class Student(models.Model):
    imie = models.CharField('imię', max_length=30)
    nazwisko = models.CharField(max_length=30)
    uczelnia = models.ForeignKey(Uczelnia, on_delete=models.SET_NULL, null=True)
    miasto = models.ForeignKey(Miasto, on_delete=models.SET_NULL, null=True)
    roks = models.CharField('rok studiów', max_length=3)
    dochod = models.DecimalField(max_digits='6', decimal_places=2)

    def __str__(self):
        return self.imie

    class Meta:
        verbose_name_plural = "studenci"

users/models.py
from django.db import models

# Create your models here.

studenci/forms.py
from django import forms

class UserLoginForm(forms.Form):
    login = forms.CharField(
        label="Twój login",
        max_length=20,
        widget=forms.TextInput()
    )

class UczelniaForm(forms.Form):
    nazwa = forms.CharField(
        label="Nazwa uczelni",
        max_length=30,
        widget=forms.TextInput()
    )

class MiastoForm(forms.Form):
    nazwa = forms.CharField(
        label="Nazwa miasta",
        max_length=30,
        widget=forms.TextInput()
    )
    kod = forms.CharField(
        label="kod miasta",
        max_length=6,
        widget=forms.TextInput()
    )

pizza/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages

# Create your views here.

def pizza(request):
    if request.method == 'POST':
        nazwa = request.POST.get('nazwa', '')
        cena = request.POST.get('cena', '')
        if len(nazwa.strip()) and len(cena.strip()):
            p = Pizza(nazwa=nazwa, cena=cena)
            p.save()
            messages.success(request, "Dodano!")
        else:
            messages.error(request, "Niepoprawne dane!")

    pizza = Pizza.objects.all()
    kontekst = {'pizza': pizza}
    return render(request, 'pizza/pizza.html', kontekst)


def index(request):
    # return HttpResponse("<h1>Witaj w aplikacji Pizza!</h1>")
    return render(request, 'pizza/index.html')

def komunikat(request):
    # return HttpResponse("<h1>Witaj!</h1>")
    return render(request, 'pizza/komunikat.html')

def zamowienie(request):
    return HttpResponse("<h1>Proszę o złożenie zamówienia</h1>")

studenci/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse

from studenci.models import Miasto, Uczelnia
from studenci.forms import UserLoginForm, UczelniaForm, MiastoForm
# Create your views here.

def index(request):
    return HttpResponse("<h1>Witaj w aplikacji Studenci!</h1>")
    # return render(request, 'studenci/index.html')

def miasta(request):
    if request.method == 'POST':
        # nazwa = request.POST.get('nazwa', '')
        # kod = request.POST.get('kod', '')
        # if len(nazwa.strip()) and len(kod.strip()):
        form = MiastoForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            m = Miasto(nazwa=form.cleaned_data['nazwa'], kod=form.cleaned_data['kod'])
            m.save()
            messages.success(request, "Dodano!")
            return redirect(reverse('studenci:miasta'))
        else:
            messages.error(request, "Niepoprawne dane!")
    else:
        form = MiastoForm

    miasta = Miasto.objects.all()
    kontekst = {'miasta': miasta, 'form': form}
    return render(request, 'studenci/miasta.html', kontekst)

def uczelnie(request):
    if request.method == 'POST':
       # nazwa = request.POST.get('nazwa', '')
        # if len(nazwa.strip()):
        form = UczelniaForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            u = Uczelnia(nazwa=form.cleaned_data['nazwa'])
            u.save()
            messages.success(request, "Dodano!")
            return redirect(reverse('studenci:uczelnie'))
        else:
            messages.error(request, "Niepoprawne dane!")
    else:
        form = UczelniaForm

    uczelnie = Uczelnia.objects.all()
    kontekst = {'uczelnie': uczelnie, 'form': form}
    return render(request, 'studenci/uczelnie.html', kontekst)

def loguj_studenta(request):
    if request.method == 'POST':
        pass
    else:
        form = UserLoginForm()
    kontekst = {'form': form}
    return render(request, 'studenci/login.html', kontekst)

users/views.py
from django.shortcuts import render

from django.contrib.auth.forms import UserCreationForm

def index(request):
    pass

def rejestruj(request):
    if request.method == 'POST':
        pass
    else:
        form = UserCreationForm()
    kontekst = {'form': form}
    return render(request, 'users/rejestruj.html', kontekst)

pizza/templates/pizza/index.html
{% extends 'szablon.html' %}

{% block tytul %}Bar pizza{% endblock tytul %}

{% block tresc %}

<h1>Witaj w barze pizza!</h1>
<p>Oferta szeroka i wszechstronna</p>

{% endblock tresc %}

pizza/templates/pizza/komunikat.html
{% extends 'szablon.html' %}

{% block tytul %}Komunikat{% endblock tytul %}

{% block tresc %}

<h1>Zapraszamy na najlepszą pizzę</h1>

{% endblock tresc %}

pizza/templates/pizza/pizza.html
{% extends 'szablon.html' %}

{% block tytul %}Lista pizz{% endblock tytul %}

{% block naglowek %}Pizze{% endblock naglowek %}

{% block tresc %}
<h2>Dodaj pizze</h2>
    <form action="." method="POST">
    {% csrf_token %}
        <input type="text" name="nazwa" size="30">
        <br>
        <input type="text" name="cena">
        <br>
        <input type="submit" value="Zapisz">
    </form>

<h2>Lista pizz</h2>
<ol>
    {% for pizza in pizze %}
        <li>{{ pizza.nazwa }}&nbsp{{ pizza.cena }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

pizza/templates/szablon.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tytul %}Projekt Django{% endblock tytul %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light">
        <a class="navbar-brand" href="http://lo1.sandomierz.pl">I LO CG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Pizza</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'pizza:index' %}" class="dropdown-item">Strona główna</a>
                        <a href="{% url 'pizza:komunikat' %}" class="dropdown-item">Komunikaty</a>
                    </div>
                </li>
                <li class="nav-item dropdown ">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Studenci</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'studenci:index' %}" class="dropdown-item">Strona główna</a>
                        <a href="{% url 'studenci:uczelnie' %}" class="dropdown-item">Uczelnie</a>
                        <a href="{% url 'studenci:miasta' %}" class="dropdown-item">Miasta</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col">
                <h1>{% block naglowek %}Projekt Django{% endblock naglowek %}</h1>

                {% block komunikaty %}
                {% if messages %}
                    <ul>
                    {% for komunikat in messages %}
                        <li>{{ komunikat }}</li>
                    {% endfor %}
                    </ul>

                {% endif %}
                {% endblock komunikaty %}

                {% block tresc %}
                {% endblock tresc %}
            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

studenci/templates/studenci/login.html
{% extends 'szablon.html' %}

{% block naglowek %}Studenci-Logowanie{% endblock naglowek %}

{% block tresc %}
    <form action="." method="POST">
    {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" value="Zapisz" class="btn">
    </form>
{% endblock tresc %}

studenci/templates/studenci/miasta.html
{% extends 'szablon.html' %}

{% block tytul %}Lista miast{% endblock tytul %}

{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}
<h2>Dodaj miasto</h2>
    <form action="." method="POST">
    {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" value="Zapisz">
    </form>

<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp{{ miasto.kod }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/uczelnie.html
{% extends 'szablon.html' %}

{% block tytul %}Lista uczelni{% endblock tytul %}

{% block naglowek %}Uczelnie{% endblock naglowek %}

{% block tresc %}

    <h1>Uczelnie</h1>
<h2>Dodaj uczelnię</h2>
    <form action="." method="POST">
    {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" value="Zapisz">
    </form>

<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnie %}
        <li>{{ uczelnia.nazwa }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

users/templates/users/rejestruj.html
{% extends 'szablon.html' %}

{% block tytul %}Rejestracja{% endblock tytul %}

{% block tresc %}

    {% if user.is_authenticated %}
        <p>Jesteś już zalogowany jako {{ user.username }}.</p>
    {% else %}
        <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
            <button type="submit">Zarejestruj</button>
        </form>
    {% endif %}

{% endblock tresc %}